### ISSUE TITLE
Extensions + lights

### ISSUE THREAD

**Issue by mklefrancois** [syoyo/tinygltf#261]
The function `SerializeGltfModel()` will serialize extensions added to Model.extensions, but immediately after, it will serialize the lights and overwrite all extensions when adding "KHR_lights_punctual".

My local fix works, but I'm sure it is not the way it should be done.

**Comment by mklefrancois** [comment]
Actually, it seems that it was planned, but there is a small typo

There is a **"!"** in front of `FindMember()` which shouldn't be there.

~~~~
    {
      json_const_iterator it;
      if(!FindMember(o, "extensions", it))
      {
        JsonAssign(ext_j, GetValue(it));
      }
    }
~~~~

**Comment by syoyo** [comment]
Oops!

https://github.com/syoyo/tinygltf/blob/3dad303bea479effc8034d5486df0f7288ac6183/tiny_gltf.h#L7312

We want to add "KHR_lights_punctual" to "model.extensions" list, so we need to rewrite a serialization logic a bit(probably we are better to move  `SerializeExtensionMap(model->extensions, o);` line after the serialization of LIGHTS.

> My local fix works

Could you post minimal reproducible .glTF file so that I can add it to regression test scenes?

**Comment by mklefrancois** [comment]
Thanks again. I hope the file in the attachment will help.

-mkl

**Comment by syoyo** [comment]
@mklefrancois Where is the attachment?

**Comment by mklefrancois** [comment]
It is a .7z, maybe the email system has revived it? It there another email
address I can send it to?

-mkl

**Comment by syoyo** [comment]
@mklefrancois Please post(attach) files to github issue.

**Comment by mklefrancois** [comment]
[extension_test.zip](https://github.com/syoyo/tinygltf/files/4628372/extension_test.zip)
Sorry, 7-zip is not a supported format. Here is a test which is using two extensions.
