### ISSUE TITLE
Accessors without bufferviews can't be loaded

### ISSUE THREAD

**Issue by Alexeyt89** [syoyo/tinygltf#328]
**Describe the issue**

Models can't be loaded if they have accessors without bufferviews

Some models, like this:
https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/Lantern/glTF-Draco/Lantern.gltf
have only accessors without bufferviews. In parsing of the accessors the bufferview index is set to -1.
The loading process interrupts with error: "accessor[0] invalid bufferView"

Loading stack:

tinhygltf::TinyGLTF::LoadASCIIFromFile
tinhygltf::TinyGLTF::LoadASCIIFromString
tinhygltf::TinyGLTF::LoadFromString <- here it stops at line 5757
Draco verison 1.4.1

**To Reproduce**
Example project:
[tinygltftest.zip](https://github.com/syoyo/tinygltf/files/6623245/tinygltftest.zip)
1) correct the path to the model in main.cpp (the model is included)
2) build and run the example.
The problem is reproducible in Qt 6.0.0 with compilers MinGW64b, MSVC2019 64b and it is reproducible if the project is built in Visual Studio 2019.
I tested all the other Khronos Group example models with draco compression, none of them can be loaded.

**Comment by syoyo** [comment]
`glview` with DRACO compression works fine. 

(
![Screenshot from 2021-06-09 21-23-09](https://user-images.githubusercontent.com/18676/121353840-43bad980-c969-11eb-9c53-4bb16d58238d.png)

You need to check glTF 2.0 spec and what is the expected behavior.

> reproducible in Qt 6.0.0 with compilers MinGW64b, MSVC2019 64b and it is reproducible if the project is built in Visual Studio 2019


This is not a reproducible environment. You need to use code/example in TinyGLTF repo.
