### ISSUE TITLE
Empty buffer round-tripping issue.

### ISSUE THREAD

**Issue by crlf0710** [syoyo/tinygltf#337]
**Describe the issue**

I think this is left over from #229. Currently the issue is this: Whenever a buffer is empty, with tinygltf i can't serialize it into file and read it back.
I did some investigation and the cause seems to be this:
URI is written as `"data:application/octet-stream;base64,"` with this code:
https://github.com/syoyo/tinygltf/blob/b86eb6c07964e5a35058b8e7a1cc4cdad6afe204/tiny_gltf.h#L6509-L6517

Then, when trying to read it back, also with tinygltf,
It is properly decode here:
https://github.com/syoyo/tinygltf/blob/b86eb6c07964e5a35058b8e7a1cc4cdad6afe204/tiny_gltf.h#L2860-L2863

After this it gets rejected,
https://github.com/syoyo/tinygltf/blob/b86eb6c07964e5a35058b8e7a1cc4cdad6afe204/tiny_gltf.h#L2914-L2916

**To Reproduce**

N/A

**Expected behaviour**

The file should round-trip successfully.

**Screenshots**

N/A

**Additional context**

N/A

**Comment by syoyo** [comment]
We may need to revisit empty URI issue: Is URI with empty buffer valid in glTF 2.0 spec?
(I couldn't find explicit description at glTF 2.0 spec site: https://www.khronos.org/registry/glTF/specs/2.0/glTF-2.0.html)
If the spec disallow empty URI, TinyGLTF should disallow serializing empty buffer.

@crlf0710 Do you have minimal glTF file with URI with empty data so that we can test it with gltf-viewer or glTF 2.0 validation tool?
