### ISSUE TITLE
Command injection via wordexp call. 

### ISSUE THREAD

**Issue by oliverchang** [syoyo/tinygltf#368]
**Describe the issue**

This is a security vulnerability. The `wordexp` call here allows arbitrary code execution https://github.com/syoyo/tinygltf/blob/0fa56e239c77cc864dc248842e8887d985cf8e3f/tiny_gltf.h#L2640 when parsing a gltf file. 

**To Reproduce**
- OS: Linux
- Compiler, compiler version, compile options: Clang 13.0.1-6

```shell
$ git clone https://github.com/syoyo/tinygltf
$ cd tinygltf && make all
$ echo '{"images":[{"uri":"a`echo iamhere > poc`"}], "asset":{"version":""}}' > payload.gltf
$ ./loader_example payload.gltf
$ cat poc
iamhere
```

**Expected behaviour**
The `echo iamhere > poc` command should not be executed and the `poc` file is not created in the CWD. 

**Additional context**
This was found by OSS-Fuzz: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=49053 

One potential fix here is to pass `WRDE_NOCMD` to `wordexp` per https://man7.org/linux/man-pages/man3/wordexp.3.html

**Comment by syoyo** [comment]
@oliverchang Thanks! In `ExpandFilePath` https://github.com/syoyo/tinygltf/blob/0fa56e239c77cc864dc248842e8887d985cf8e3f/tiny_gltf.h#L1266 `wordexp` is used to expand file path(i.e, expand environment variable, expand tilde(`~`) when a file path contains such symbol). 

But according to glTF spec https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#uris , `uri` must be URI/IRI, so file(resource) path should not contain environment variables and tilde, so we need to use URI decoder/encoder instead of `ExpandFilePath`.

Related: https://github.com/syoyo/tinygltf/issues/337

**Comment by syoyo** [comment]
Disabled file path expansion(so no `wordexp` anymore) in this commit: https://github.com/syoyo/tinygltf/commit/52ff00a38447f06a17eab1caa2cf0730a119c751

TODO: Proper/strict decoding/encoding of  URI asset path: https://github.com/syoyo/tinygltf/blob/9117abb45d948b025b533143f678af65c258e1eb/tiny_gltf.h#L2202

**Comment by oliverchang** [comment]
Thank you very much for the amazingly fast fix @syoyo ! 

Would it be possible to create a security advisory (and CVE) for this via https://github.com/syoyo/tinygltf/security/advisories so downstream users are notified?

**Comment by syoyo** [comment]
@oliverchang Oh, I didn't know Github has a `Security` page 😮  Will take a look it.

**Comment by oliverchang** [comment]
Hi @syoyo, have you had a chance to try generating an advisory for this issue? It's a crucial part of making sure users of this library are notified of vulnerabilities (and that they need to update).

**Comment by oliverchang** [comment]
FYI we've requested CVE-2022-3008 for this vulnerability: https://nvd.nist.gov/vuln/detail/CVE-2022-3008
