### ISSUE TITLE
Consider using `nlohmann::json` instead of just `json`

### ISSUE THREAD

**Issue by DavidSM64** [syoyo/tinygltf#406]
**Describe the issue**

In my project I have been using the SimpleJSON library (https://github.com/nbsdx/SimpleJSON) for creating/loading json files, which uses the namespace `json` for its classes. When trying to use the tinygltf library I get ambiguity errors because you are also using `json`. I solved this issue in my own project by changing `json` to `nlohmann::json` in tiny_gltf.h

**To Reproduce**

- OS: Ubuntu (Under WSL2)
- Compiler: g++

**Expected behaviour**

Changing `json` to `nlohmann::json` in the nlohmann implementation fixes the problem. I know it would be annoying, but it should help resolve future conflicts.

**Comment by syoyo** [comment]
Oh, I see!

 `json` namespace is not exposed to tinygltf public API, so it should be safe to rename it(for example, `json_backend`)

Also, we'd be better to wrap some implementation code with `detail`(or `internal`) namespace(instead of anonymous namespace https://github.com/syoyo/tinygltf/blob/6dba104c54bebd6c6b34f589272a06da509156e2/tiny_gltf.h#L1708 ) to avoid potential namespace conflicts issue further. i.e.

```c++

namespace tinygltf {
namespace detail {

using json_backend = nlohnann::json;

...

void JsonParse(...) {
  doc = json_backend::parse(...)
}

} // detail
} // tinygltf
```

PR is much appreciated!

**Comment by syoyo** [comment]
🙏
