### ISSUE TITLE
[Question] get mesh position datas from buffer

### ISSUE THREAD

**Issue by ladiszlai** [syoyo/tinygltf#71]
I want to print all of the vertex positions of the mesh to the screen, but I have no idea how. Can someone help me out please ?
What I have already done:
https://pastebin.com/PiGencLV

sry for the pastebin but that "Insert code" is useless (my first part of the code is out of the highlight box)

**Comment by syoyo** [comment]
You can use ```(three backquotes to wrap codes)

**Comment by ladiszlai** [comment]
Thanks, and can you help me ? I also asked a question here : https://stackoverflow.com/questions/50074638/c-get-vertex-arrays-from-buffer-gltf-model-loader

No one wants to help me, but I think it is basic programming skill.

**Comment by syoyo** [comment]
You are first better to study 3D graphics programming > http://graphicscodex.com/

**Comment by ladiszlai** [comment]
If you can't do it, how did you made the full loader ? lol

**Comment by ladiszlai** [comment]
Nope, that code is wrong because it just gets the buffer not the vertex positions.. buffer can contain more than just vertex coordinates. I already figured out the script and working for me, but I will not share until Syoyo learnt that stuff what he linked here xD

**Comment by syoyo** [comment]
Initial question is not expressive and it looks @ladiszlai find a solution, so close the issue.

**Comment by CheezBoiger** [comment]
For future reference:

A little late on this one, but here's a way to access data from buffers when querying. 

The specs **literally** tell you how to access contents within a buffer, with the exception of it not telling you that 'count' is the number of values, that define some data type, of which the buffer view refers to within the buffer. Accessing vertex data from a gltf file you do as so:
```C++
const tinygltf::Model& model;
// Assuming you loaded the gltf model.
 ...
for each primitive in a mesh...
const tinygltf::Accessor& accessor = model.accessors[primitive.attributes["POSITION"]];
const tinygltf::BufferView& bufferView = model.bufferViews[accessor.bufferView];
```
finally, to obtain and read out each vertex position:
```C++
// cast to float type read only. Use accessor and bufview byte offsets to determine where position data 
// is located in the buffer.
const tinygltf::Buffer& buffer = model.buffers[bufferView.buffer];
// bufferView byteoffset + accessor byteoffset tells you where the actual position data is within the buffer. From there
// you should already know how the data needs to be interpreted.
const float* positions = reinterpret_cast<const float*>(&buffer.data[bufferView.byteOffset + accessor.byteOffset]);
// From here, you choose what you wish to do with this position data. In this case, we  will display it out.
for (size_t i = 0; i < accessor.count; ++i) {
          // Positions are Vec3 components, so for each vec3 stride, offset for x, y, and z.
           std::cout << "(" << positions[i * 3 + 0] << ", "// x
                            << positions[i * 3 + 1] << ", " // y
                            << positions[i * 3 + 2] << ")" // z
                            << "\n";
}
proceed to next primitive...
```
You can also incorporate this for indices, normals, texcoords, joints, weights, etc (because the component and data types are also in the specs) of a given primitive as well. Keep in mind that even though position should always be available for primitives, other attributes may not be available.

**Also**, you don't need to slander syoyo for making a tool as helpful as this, read the specs first, and then ask where you are specifically stuck (you don't specify how and what hints at where to start reading within the buffer, for instance). And while it's okay that you have found the solution, it would be appreciative if you share how you solved this problem, so that others whom may get stuck here as well, won't have to ask the same questions in the future, not to show off and become a ****.

here's a nice reference from the gltf 2.0 docs from which I hoped the asker has read:
![accessdata](https://user-images.githubusercontent.com/10396295/40645279-c0b5003a-62da-11e8-9ead-23f773147079.png)

Hopefully this will be hopeful for people.

**Comment by ladiszlai** [comment]
Yeah you alright and I'm sry, so here is my solution its almost like yours but I don't store the full vertices memory, I keep pushing the datas to a struct:

```
			for (int i = 0; i < vertexaccess.count; ++i)
			{
				char* vertexarray = new char[12];
				int arraytemp = 0;

				for (int j = (vertexaccess.byteOffset + vertexbview.byteOffset) + (i * 12); j < (vertexaccess.byteOffset + vertexbview.byteOffset) + (i * 12) + 12; ++j)
				{
					vertexarray[arraytemp] = vertexbuffer.data[j];
					++arraytemp;
				}

				FloatVec3& coordinates = *reinterpret_cast<FloatVec3*>(vertexarray);
				
				cout << coordinates.x << endl << coordinates.y << endl << coordinates.z << endl;

				delete[] vertexarray;
			}
 ```

**Comment by syaifulnizamyahya** [comment]
In case anyone looking how to get gltf vertices :
```

void printVertices(const tinygltf::Model &model) {
  for (const auto &mesh : model.meshes) {
    for (const auto &primitive : mesh.primitives) {
      if (primitive.attributes.find("POSITION") != primitive.attributes.end()) {
        const tinygltf::Accessor &accessor =
            model.accessors[primitive.attributes.find("POSITION")->second];
        const tinygltf::BufferView &bufferView =
            model.bufferViews[accessor.bufferView];
        const tinygltf::Buffer &buffer = model.buffers[bufferView.buffer];

        const float *positions = reinterpret_cast<const float *>(
            &buffer.data[bufferView.byteOffset + accessor.byteOffset]);

        size_t vertexCount = accessor.count;

        std::cout << "Mesh: " << mesh.name
                  << ", Primitive: " << primitive.material << std::endl;
        for (size_t i = 0; i < vertexCount; ++i) {
          float x = positions[i * 3 + 0];
          float y = positions[i * 3 + 1];
          float z = positions[i * 3 + 2];
          std::cout << "Vertex " << i << ": (" << x << ", " << y << ", " << z
                    << ")" << std::endl;
        }
      }
    }
  }
}
```
